### ISSUE TITLE
impossible d'ajouter aux collections

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_albums#12]
Depuis un certain temps bien incertain, Je n'arrive plus à ajouter des media à des collections, alors qu'avant cela fonctionnait.
Je crains bien que ce ne soit mes bidouilles ou ma configuration, mais j'ai le problème aussi sur le site de geodiversite.net, alors peut-être n'est-ce pas seulement chez moi ?

**Comment by brunob** [comment]
Je viens de tester en local et ça fonctionne très bien, idem sur geodiversite.net.

> Je crains bien que ce ne soit mes bidouilles ou ma configuration

On va dire que c'est ça :)

**Comment by ubiquando** [comment]
Bon, alors j'ai un peu creusé.
Sur 3 sites, "même" symptôme, impossible d'affecter des collections à des media, et 3 causes différentes...
- sur l'un chez moi, c'était qu'il fallait paramétrer select2 pour être accessible sur le site public; je l'ai ajouté au brouillon de doc...
- sur l'autre c'est que je n'avais pas reporté proprement les modifs des formulaires depuis le passage à select2
- mais sur le troisième, c'est geodiversite.net, et là je persiste, je n'arrive plus à mettre mes media dans mes collections !
De mon côté, sur geodiversite.net depuis la page d'un media :
- j'ai le message d'erreur "Les résultats ne peuvent pas être chargés" en cliquant dans le champ "ajouter à la collection"
-  la console m'indique une erreur 403 sur 
https://www.geodiversite.net/selecteur.api/geol_albums?id_article=2278&id_auteur=308&php=&q=Chartreuse

bizarre, non ?

**Comment by brunob** [comment]
> sur l'un chez moi, c'était qu'il fallait paramétrer select2 pour être accessible sur le site public; je l'ai ajouté au brouillon de doc...

Ha bien vu, c'est un bug il faut que le plugin force l'insertion des scripts de select2 dans le public à l'installation. À noter, on utilise déjà `_SELECTEUR_GENERIQUE_ACTIVER_PUBLIC` pour que les scripts de selecteur_generique soient insérés dans le public, mais depuis que ce plugin utilise select2, ça ne peut pas fonctionner si l'option de config de select2 pour activer l'insertion de ses scripts dans le public n'est pas active. Donc, bug ici ou dans selecteur_generique ? Voir https://git.spip.net/spip-contrib-extensions/selecteur_generique/-/issues/6

En attendant on va déjà fixer le bug chez nous.

**Comment by brunob** [comment]
> la console m'indique une erreur 403 sur
https://www.geodiversite.net/selecteur.api/geol_albums?id_article=2278&id_auteur=308&php=&q=Chartreuse

Vu ! Cela vient de ce qui semble être un changement dans la v2 de selecteur_generique cf :

> Le retour de l’api json se fait sur l’autorisation autocomplete, qui est par défaut
sur l’autorisation d’accès à l’espace privé.

ref https://contrib.spip.net/Selecteur-generique-v2-avec-autocompletion

Fix en cours de préparation.

**Comment by brunob** [comment]
C'est dans la boite et en prod, on peut fermer, et merci pour le signalement.

**Comment by ubiquando** [comment]
une fois de plus, merci pour les modifs rapides !
Bon, je n'ai pas bien pigé, si c'est en prod aussi sur geodiversite.net ?
Parce que je n'arrive toujours pas à affecter de collections à mes media... **lorsque je ne suis pas admin**.
Même pbm chez moi après mise à jour des derniers commits.
Chez moi, ça fonctionne bien... quand je suis connecté comme admin.

**Comment by ubiquando** [comment]
Encore un truc : même problème avec l'ajout de **tags**. Possible en tant qu'admin, pas en tant que visiteur connecté.
 "Les résultats ne peuvent pas être chargés"

**Comment by brunob** [comment]
Pour les albums je vois le pb, le sélecteur est nommé `geol_albums` ce qui pose problème dans l'API autoriser car notre autorisation se nomme donc `autoriser_geol_albums_autocomplete_dist` dans laquelle il y a un _ de trop. Il faudrait que je renomme le selecteur en geolalbums, grml de grml.

Vu, `autorisyer_type()` transforme geol_albums en geolalbum, fix en cours.

**Comment by brunob** [comment]
> Encore un truc : même problème avec l'ajout de **tags**. Possible en tant qu'admin, pas en tant que visiteur connecté.

C'est le même problème, je viens de le corriger dans geodiversite.

**Comment by ubiquando** [comment]
Super, on avance, merci !
- c'est bon pour les tags
- c'est presque bon pour les collections, sauf que... on ne voit que les collections de l'auteur, et non celles partagées par d'autres auteurs.
- je suppose que tu n'as pas envoyé les modifs sur geodiversite.net, en tout cas ça ne fonctionne pas pour moi.

**Comment by brunob** [comment]
>     * c'est presque bon pour les collections, sauf que... on ne voit que les collections de l'auteur, et non celles partagées par d'autres auteurs.

C'est bien le principe, il faut rejoindre une collection "collective" avant de pouvoir y ajouter des documents.

>     * je suppose que tu n'as pas envoyé les modifs sur geodiversite.net, en tout cas ça ne fonctionne pas pour moi.

On ne peut pas être partout à la fois ;o C'est up maintenant.

PS : tu en es où avec la doc ? Tu penses qu'on pourra la publier prochainement ?

**Comment by ubiquando** [comment]
> > ```
> > * c'est presque bon pour les collections, sauf que... on ne voit que les collections de l'auteur, et non celles partagées par d'autres auteurs.
> > ```
> 
> C'est bien le principe, il faut rejoindre une collection "collective" avant de pouvoir y ajouter des documents.

Oups... j'avais oublié qu'il fallait d'abord aller dans les collections collectives pour y participer... j'avais mal lu "ma" doc ! ;)
 
> > ```
> > * je suppose que tu n'as pas envoyé les modifs sur geodiversite.net, en tout cas ça ne fonctionne pas pour moi.
> > ```
> 
> On ne peut pas être partout à la fois ;o C'est up maintenant.

Je suis déçu, j'y croyais presque...  En effet ça marche tip-top.
> 
> PS : tu en es où avec la doc ? Tu penses qu'on pourra la publier prochainement ?

Oui, je prévois de refaire une installation depuis zéro la semaine prochaine pour vérifier si ce qu'on avait écrit il y a un moment reste valable. Il restera probablement des erreurs et/ou imprécisions, je te préviendrai pour que tu vérifies.
Merci encore !
