### ISSUE TITLE
utilisation des collections

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_albums#3]
Je n'arrive pas à utiliser les collections.
- menu Edition > collections 
je ne vois pas les collections, qu'elles soient créées via geodiv ou depuis l'admin, bien qu'elles existent dans la base.
Si je modifie  plugins/auto/collections/v1.5.2/prive/objets/liste/collections.html, elles s'affichent si j'enlève "{id_mot?}" dans la boucle d'affichage... pas pigé pourquoi

- impossible d'attacher un media à une collection, qu'elle soit personnelle ou collective, créée par l'auteur ou par l'admin, qu' l'auteur soit propriétaire ou non du media : "L’association à la collection a échoué."

spip 3.2.11, plugin geodiversite_install; php 7.0

**Comment by ubiquando** [comment]
Trouvé (en partie) !
Il faut absolument utiliser le .htaccess de spip, sinon pas de sélecteur générique !
Ceci dit, l'entrée de menu Edition>collections n'affiche toujours pas toutes les collections, juste celles ayant au moins un media, semble-t-il.

**Comment by brunob** [comment]
Les collections s'utilisent depuis l'espace public, pas depuis le privé, et pour le htaccess ça doit être mentionné dans le readme de geodiv si je ne me trompe pas (et certainement dans la doc des plugins qu'on utilise). On peut fermer ?
