### ISSUE TITLE
saisie du descriptif de la collection

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_albums#4]
Je propose de modifier content/collection.html (issu du plugin collections), en affichant le div du champ #DESCRIPTIF même s'il est vide, afin de permettre de remplir ce champ dans la partie publique; sinon, le crayon ne s'affiche pas, et je n'ai pas trouvé comment remplir  ce champ, ce qui est bien dommage.
(ligne 36)

**Comment by brunob** [comment]
Je ne comprends pas, la page affiche bien "Pas encore de descriptif." s'il n'y en a pas et l'élément est bien cliquable pour édition avec crayons. Je ferme, mais n'hésite pas à commenter si ça ne fonctionne pas chez toi.
