### ISSUE TITLE
articles cachés si absents d'une collection

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_albums#9]
dans la partie /ecrire, les articles n'étant pas dans une collection disparaissent comme par magie.
En creusant un peu, je constate que la liste des articles de prive/objets/liste/articles n'affichent effectivement pas ces articles.
Si on enlève le {id_?} , premier critère de la boucle, les articles disparus réapparaissent.
Bon, je ne sais pas bien à quoi correspond ce {id_?} .
Cela n'a probablement pas de rapport. Mais les articles disparus ont comme point commun de ne pas apparaître dans une collection.
spip 4.0.9, php7.4.33, geodiversite4.0.0

**Comment by brunob** [comment]
Je crois bien que je confirme, à corriger donc. Le bug est-il toujours présent si le plugin des albums est désactivé ?

**Comment by brunob** [comment]
Requête sur un SPIP de base :

```sql
SELECT articles.id_article, 0 as points, '', articles.titre, articles.lang, articles.statut, articles.id_rubrique, articles.surtitre, articles.titre AS titre_rang, articles.soustitre, articles.date
FROM spip_articles AS `articles`
WHERE (articles.statut = 'prop')
	AND (articles.id_rubrique > "0")
GROUP BY articles.id_article
ORDER BY articles.date DESC, articles.titre
```

La même sur geodiv avec le plugin des albums, qui est donc le responsable :

```sql
SELECT articles.id_article, 0 as points, '', articles.titre, articles.lang, articles.statut, articles.id_rubrique, articles.surtitre, L5.rang, articles.soustitre, articles.date
FROM spip_articles AS `articles`  
INNER JOIN spip_collections_liens AS L5 ON ( L5.id_objet = articles.id_article AND L5.objet='article')
WHERE (L5.objet = 'article')
	AND (articles.statut = 'prop')
	AND (articles.id_rubrique > "0")
GROUP BY articles.id_article
ORDER BY articles.date DESC, articles.titre
```

On voit bien que le plugin des albums ajoute à tort une jointure en trop, je déplace le ticket sur le bon repo.

**Comment by brunob** [comment]
Après recherche, il semble que ça soit la balise `#RANG` dans `prive/objets/liste/articles.html` qui force la jointure vers `spip_collections_liens`.

Mais le problème vient certainement du critère `{id_?}` comme tu le dis, si je reviens sur ce commit de SPIP https://git.spip.net/spip/spip/commit/171d66bf4b0c77101ac70a70f4a63f2d17b961ea la jinture sur `spip_collections_liens` n'est plus présente.

**Comment by brunob** [comment]
Bon, je crois que je vais pas m'emmerder et utiliser le pipeline `exclure_id_conditionnel` pour ça, le patch suivant fixe le bug : 

```diff
diff --git a/geol_albums_pipelines.php b/geol_albums_pipelines.php
index c0e3081..b91b9e3 100644
--- a/geol_albums_pipelines.php
+++ b/geol_albums_pipelines.php
@@ -132,3 +132,17 @@ function geol_albums_collections_liste_genres($flux) {
 
 	return $flux;
 }
+
+/**
+ * Enlever les id_ de la table spip_collections du critère selections conditionnelles,
+ * ailleurs que sur cette table
+ *
+ * @param array $flux
+ * @return array
+ */
+function geol_albums_exclure_id_conditionnel($flux) {
+	if ($flux['args']['table'] !== 'spip_collections') {
+		$flux['data'] = array_merge($flux['data'], ['id_collection']);
+	}
+	return $flux;
+}
\ No newline at end of file
diff --git a/paquet.xml b/paquet.xml
index 7616300..6396b5f 100644
--- a/paquet.xml
+++ b/paquet.xml
@@ -28,7 +28,8 @@
 	<pipeline nom="affiche_milieu" inclure="geol_albums_pipelines.php" />
 	<pipeline nom="optimiser_base_disparus" inclure="geol_albums_pipelines.php" />
 	<pipeline nom="collections_liste_types" inclure="geol_albums_pipelines.php" />
-	<pipeline nom="collections_liste_genres" inclure="geol_albums_pipelines.php" /> 
+	<pipeline nom="collections_liste_genres" inclure="geol_albums_pipelines.php" />
+	<pipeline nom="exclure_id_conditionnel" inclure="geol_albums_pipelines.php" />
 	
 	<necessite nom="geol" compatibilite="[4.0.0;[" />
 	<necessite nom="selecteurgenerique" compatibilite="[1.1.7;[" />

```
